services:
  db:
    image: postgres:14
    container_name: postgres-magasin
    environment:
      POSTGRES_DB: magasin_api
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - magasin_net

  api1:
    image: nathanlamyy/magasin-backend:latest
    container_name: api1
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://magasin_user:secret@db:5432/magasin_api
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"
    networks:
      - magasin_net

  api2:
    image: nathanlamyy/magasin-backend:latest
    container_name: api2
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://magasin_user:secret@db:5432/magasin_api
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"
    networks:
      - magasin_net

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - api1
      - api2
    networks:
      - magasin_net

    redis:
      image: redis:6
      ports:
        - "6379:6379"
      networks:
        - magasin_net

volumes:
  postgres_data:

networks:
  magasin_net:
